const classMapping = {
    'FiltrerUnCritere': FiltrerUnCritere,
    'FiltrerPlusieursCriteres':FiltrerPlusieursCriteres,
    'FormulaireAjoutUtilisateur':FormulaireAjoutUtilisateur,
    'FormValidator': FormValidator,
    'Header': Header,
    'Voiture': Voiture,
    'VoirPlus': VoirPlus,
    'Profil': Profil,
    'Modele': Modele,
    'VoitureDetail': VoitureDetail,
    'FormulaireAjoutVoiture': FormulaireAjoutVoiture,
    'FormulaireModifierVoiture': FormulaireModifierVoiture,
    'ConfirmationList' : ConfirmationList,
    'GroupeMotopropulseur' : GroupeMotopropulseur,
    'FormulaireAjoutMotoPropulseur' : FormulaireAjoutMotoPropulseur,
    'FormulaireMisAjourMotoPropulseur' :FormulaireMisAjourMotoPropulseur,
    'Chassis' : Chassis,
    'FormulaireAjoutChassis' : FormulaireAjoutChassis,
    'FormulaireMisAjourChassis' :FormulaireMisAjourChassis,
    'TypeCarburant' : TypeCarburant,
    'FormulaireAjoutTypeCarburant' : FormulaireAjoutTypeCarburant,
    'FormulaireMisAjourTypeCarburant' :FormulaireMisAjourTypeCarburant

};