DROP TABLE IF EXISTS facture;
DROP TABLE IF EXISTS ligneCommande;
DROP TABLE IF EXISTS commande;
DROP TABLE IF EXISTS listeImage;
DROP TABLE IF EXISTS voiture;
DROP TABLE IF EXISTS chassis;
DROP TABLE IF EXISTS typeCarburant;
DROP TABLE IF EXISTS groupeMotopropulseur;
DROP TABLE IF EXISTS modele;
DROP TABLE IF EXISTS marque;
DROP TABLE IF EXISTS fabricant;
DROP TABLE IF EXISTS connexion;
DROP TABLE IF EXISTS utilisateur;
DROP TABLE IF EXISTS typeUtilisateur;
DROP TABLE IF EXISTS ville;
DROP TABLE IF EXISTS province;
DROP TABLE IF EXISTS statut;
DROP TABLE IF EXISTS expedition;
DROP TABLE IF EXISTS modePaiement;
DROP TABLE IF EXISTS transmission;




